#!/bin/bash

usg() {
    echo 'usage h5vtk dirname h5part
  converts h5part of vtk files' >&2
    exit
}

msg() { printf "$@" >&2; }
err() { msg 'h5vtk: '; msg "$@"; msg '\n'; exit 1; }

if test $# -ne 0 -a "$1" = -h; then usg; fi

if test $# -eq 0; then err 'not enough arguments'; fi
d="$1"; shift

if test $# -eq 0; then err 'not enough arguments'; fi
s="$1"; shift

if test ! -f "$s"; then err 'fail to load %s' "$s"; fi

t=/tmp/h5vtk.$$

trap 'rm -rf $t' 0 1 2 3 15

if ! h5bop "$t" "$s"; then err 'h5bop failed'; fi
mkdir -p "$d" 2> /dev/null
if test ! -d "$d"; then err 'cannot create directory %s' "$d"; fi

(cd "$t"
 for b in *.bop
 do v=`basename $b .bop`
    v=$v.vtk
    bop2vtk $v $b
 done)

for v in $t/*.vtk; do mv $v "$d"; done

# TEST: h5vtk
# h5vtk d test_data/all.h5part
# mv d/0000.vtk h.out.vtk
#
